name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev  # Trigger on dev branch (can change to 'main' if needed)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build Docker images using docker-compose.yml
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the built Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push
