name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        version: '20.10'  # Install the latest stable Docker version

    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose.yml build  # Build the images using docker-compose.yml
        docker-compose -f docker-compose.yml push   # Push the images to Docker Hub
