name: Test-to-Dev Workflow

on:
  pull_request:
    branches:
      - dev  # Trigger this workflow on pull requests to 'dev'

jobs:
  build_and_merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and run frontend unit tests
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend unit tests
        run: |
          cd frontend
          npm test -- --ci --silent --coverage

      # Install dependencies and run backend unit tests
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run backend unit tests
        run: |
          cd backend
          npm test -- --ci --silent --coverage

      # Merge PR to dev if all tests pass
      - name: Merge PR to dev
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add this line to set the token
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge

      # Push dev to main after successful tests and PR merge
      - name: Push dev to main
        if: success()  # Only runs if previous steps were successful i
        run: |
          git fetch origin dev  # Fetch the dev branch from the remote
          git checkout dev  # Check out the dev branch
          git pull origin dev  # Ensure the latest dev is pulled
          git config --global user.name "github-actions[bot]"  # Set the user name
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Set the email
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} dev:main  # Push dev to main
