name: Test-to-Dev Workflow

on:
  pull_request:
    branches:
      - dev
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install and run tests for frontend
      - name: Install and test frontend
        run: |
          cd frontend
          npm install
          npm test -- --ci --silent --coverage

      # Install and run tests for backend
      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm test -- --ci --silent --coverage

      # Merge dev into main programmatically
      - name: Automate merge to main
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge dev
          git push origin main
