name: Dev-to-Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and run tests for frontend
      - name: Install and test frontend
        run: |
          cd frontend
          npm install
          npm test -- --ci --silent --coverage

      # Install dependencies and run tests for backend
      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm test -- --ci --silent --coverage

      # Run end-to-end tests
      - name: Run e2e tests
        run: |
          cd e2e-tests
          npm install
          npm test

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Build Docker images
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push
