name: Test-to-Dev Workflow

on:
  pull_request:
    branches:
      - dev  # Trigger this workflow on pull requests to 'dev'

jobs:
  build_and_merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and run frontend unit tests
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend unit tests
        run: |
          cd frontend
          npm test -- --ci --silent --coverage

      # Install dependencies and run backend unit tests
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run backend unit tests
        run: |
          cd backend
          npm test -- --ci --silent --coverage

      # Merge PR to dev if all tests pass
      - name: Merge PR to dev
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add this line to set the token
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge

      # Pull main to resolve any conflicts and push dev to main
      - name: Pull main and push dev to main
        if: success()
        run: |
          git fetch origin main  # Fetch the latest changes from main
          git checkout dev      # Ensure you're on the dev branch
          git pull origin main   # Pull the latest changes from main into dev
          git push origin dev:main  # Push dev to main
